name: sl_travel_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.1.3
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  google_maps_flutter: ^0.5.21+3
  text_to_speech_api: ^0.0.1
  audioplayer: ^0.5.2
  image_picker: ^0.6.1+4
  curl: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900